package shared

import "DeepSeek_Web_To_API/internal/promptcompat"

// ApplyThinkingInjection rewrites a StandardRequest to surface the
// ds2api-managed thinking instructions to the upstream model. When the
// request carries tools, the long workflow playbook is hoisted into the
// system message (so it survives upstream no-thinking fast-paths and is
// not duplicated against the user prompt), and only the short
// reasoning-effort encouragement stays at the latest user-message tail.
// When the request has no tools the legacy single-block behavior is
// kept — without tools the playbook is dead weight.
//
// A non-empty custom prompt configured by the operator (via
// ConfigReader.ThinkingInjectionPrompt) overrides the split entirely:
// the operator gets exactly what they wrote at the user-message tail.
func ApplyThinkingInjection(store ConfigReader, stdReq promptcompat.StandardRequest) promptcompat.StandardRequest {
	if store == nil || !store.ThinkingInjectionEnabled() || !stdReq.Thinking {
		return stdReq
	}

	customPrompt := store.ThinkingInjectionPrompt()
	hasTools := false
	if tools, ok := stdReq.ToolsRaw.([]any); ok && len(tools) > 0 {
		hasTools = true
	}

	messages := stdReq.Messages
	changed := false

	useSplit := customPrompt == "" && hasTools
	if useSplit {
		// Push playbook into the system message first so the subsequent
		// FinalPrompt build picks it up alongside the tool-format RULES
		// generated by injectToolPrompt.
		next, sysChanged := promptcompat.PrependPlaybookToSystem(messages, promptcompat.ToolChainPlaybookPrompt)
		if sysChanged {
			messages = next
			changed = true
		}
		next, userChanged := promptcompat.AppendThinkingInjectionPromptToLatestUser(messages, promptcompat.ReasoningEffortPrompt)
		if userChanged {
			messages = next
			changed = true
		}
	} else {
		next, userChanged := promptcompat.AppendThinkingInjectionPromptToLatestUser(messages, customPrompt)
		if userChanged {
			messages = next
			changed = true
		}
	}

	if !changed {
		return stdReq
	}

	finalPrompt, toolNames := promptcompat.BuildOpenAIPrompt(messages, stdReq.ToolsRaw, "", stdReq.ToolChoice, stdReq.Thinking)
	if len(toolNames) == 0 && len(stdReq.ToolNames) > 0 {
		toolNames = stdReq.ToolNames
	}
	stdReq.Messages = messages
	stdReq.FinalPrompt = finalPrompt
	stdReq.ToolNames = toolNames
	return stdReq
}
