#!/usr/bin/env python3
"""One-shot prod hardening: push our deploy public key, disable password
auth on sshd, rotate root password to a random 40-char value.

After this script runs successfully, scripts/deploy_107.py will pick up
the private key at build/ds2api_deploy automatically and the prod root
password becomes irrelevant — even if it's leaked anywhere (transcript,
shell history, screen recording) the host no longer accepts password
auth.

USAGE — operator runs this, NOT the AI:

    cd /e/ds2api
    export DST_HOST='<prod ip>'           # only host is set in env
    python3 scripts/setup_prod_keyauth.py
    # script will prompt for the prod root password via getpass
    # (no echo, not stored, not logged)

Requires: paramiko, build/ds2api_deploy.pub generated by ssh-keygen.
"""
from __future__ import annotations
import getpass
import io
import os
import secrets
import string
import sys

import paramiko

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
PUBKEY_PATH = os.path.join(REPO_ROOT, "build", "ds2api_deploy.pub")


def run(client: paramiko.SSHClient, cmd: str, ok_codes=(0,), label: str = "") -> str:
    _, o, e = client.exec_command(cmd, timeout=30)
    out = o.read().decode("utf-8", "replace")
    err = e.read().decode("utf-8", "replace")
    rc = o.channel.recv_exit_status()
    print(f"[remote] $ {label or cmd[:60]}")
    if out.strip():
        print(out.rstrip())
    if err.strip():
        print(f"[stderr] {err.rstrip()}")
    if rc not in ok_codes:
        raise SystemExit(f"command failed (rc={rc}): {label or cmd}")
    return out


def main() -> None:
    host = os.environ.get("DST_HOST", "").strip()
    if not host:
        host = input("Prod host (DST_HOST not set): ").strip()
    if not host:
        print("DST_HOST required", file=sys.stderr)
        sys.exit(2)
    user = os.environ.get("DST_USER", "root").strip() or "root"

    if not os.path.exists(PUBKEY_PATH):
        print(f"missing {PUBKEY_PATH} — run ssh-keygen first", file=sys.stderr)
        sys.exit(2)
    with open(PUBKEY_PATH, "r", encoding="utf-8") as f:
        pubkey = f.read().strip()
    if not pubkey.startswith("ssh-"):
        print(f"public key file does not look like an OpenSSH public key", file=sys.stderr)
        sys.exit(2)

    print(f"[setup] target = {user}@{host}")
    print("[setup] enter the prod root password ONCE; it will not be echoed,")
    print("        not stored, and not used after this script exits:")
    pwd = getpass.getpass("Prod root password: ")
    if not pwd:
        print("password required", file=sys.stderr)
        sys.exit(2)

    new_root_pwd = "".join(secrets.choice(string.ascii_letters + string.digits + "._-") for _ in range(40))

    c = paramiko.SSHClient()
    c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    c.connect(host, username=user, password=pwd, allow_agent=False, look_for_keys=False, timeout=30)
    try:
        # Step 1: install pubkey into authorized_keys (idempotent)
        run(c, "mkdir -p ~/.ssh && chmod 700 ~/.ssh", label="ensure ~/.ssh exists")
        # Use a here-doc to avoid embedding the pubkey on the command line directly
        # (it's public so this is fine, but the pattern is good hygiene).
        cmd_install = (
            "set -e; "
            "key=$(cat <<'PUBKEY_EOF'\n"
            f"{pubkey}\n"
            "PUBKEY_EOF\n"
            "); "
            'touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys; '
            'grep -qxF "$key" ~/.ssh/authorized_keys || printf "%s\\n" "$key" >> ~/.ssh/authorized_keys'
        )
        run(c, cmd_install, label="install pubkey into authorized_keys")

        # Step 2: disable password authentication on sshd
        run(
            c,
            "sed -i 's/^[#[:space:]]*PasswordAuthentication[[:space:]]\\+.*/PasswordAuthentication no/' /etc/ssh/sshd_config && "
            "grep -q '^PasswordAuthentication no' /etc/ssh/sshd_config || echo 'PasswordAuthentication no' >> /etc/ssh/sshd_config",
            label="disable PasswordAuthentication in sshd_config",
        )
        run(
            c,
            "sed -i 's/^[#[:space:]]*PermitRootLogin[[:space:]]\\+.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config && "
            "grep -q '^PermitRootLogin' /etc/ssh/sshd_config || echo 'PermitRootLogin prohibit-password' >> /etc/ssh/sshd_config",
            label="lock PermitRootLogin to prohibit-password",
        )

        # Step 3: reload sshd config (does NOT kick existing sessions)
        run(c, "systemctl reload sshd 2>/dev/null || systemctl reload ssh 2>/dev/null || service ssh reload", label="reload sshd")

        # Step 4: rotate root password to a random unrecoverable value.
        # The old leaked password becomes useless instantly.
        cmd_rotate = f"echo 'root:{new_root_pwd}' | chpasswd"
        run(c, cmd_rotate, label="rotate root password to random 40-char value")

        # Step 5: verification — list authorized_keys and confirm sshd_config
        run(c, "wc -l < ~/.ssh/authorized_keys", label="authorized_keys line count")
        run(c, "grep -E '^(PasswordAuthentication|PermitRootLogin) ' /etc/ssh/sshd_config", label="effective sshd auth config")
        print("[done] prod is now key-only. Old password is rotated to a random unknown value.")
        print("       Future deploys: just run scripts/deploy_107.py with DST_HOST set.")
    finally:
        c.close()


if __name__ == "__main__":
    main()
